# Generated by Django 3.1.4 on 2020-12-10 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-pk', '-updated', '-created', 'title']},
        ),
    ]
