# Generated by Django 3.1.4 on 2021-03-09 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postings', '0002_remove_comment_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='sidi_only',
            field=models.BooleanField(default=False),
        ),
    ]
