# Generated by Django 3.1.4 on 2020-12-10 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postings', '0002_auto_20201210_1657'),
        ('postings', '0002_auto_20201210_1619'),
    ]

    operations = [
    ]
