# Generated by Django 3.1.4 on 2020-12-10 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postings', '0003_merge_20201210_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.IntegerField(choices=[(1, 'Notice'), (2, 'Lostandfound'), (3, 'Job'), (4, 'Petc'), (5, 'Gw'), (6, 'Wff'), (7, 'Aetc')]),
        ),
    ]
