# Generated by Django 3.1.4 on 2021-03-09 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postings', '0004_auto_20210310_0115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.IntegerField(choices=[(1, 'Notice'), (2, 'Promotionandevent'), (3, 'Job'), (4, 'Somoim'), (5, 'Gw'), (6, 'Wff'), (7, 'Aetc')]),
        ),
    ]
