# Generated by Django 3.1.4 on 2021-03-17 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postings', '0005_auto_20210310_0122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.IntegerField(choices=[(1, 'News'), (2, 'Notice'), (3, 'Promotionandevent'), (4, 'Job'), (5, 'Lostandfound'), (6, 'Gw'), (7, 'Wff'), (8, 'Aetc'), (9, 'Life'), (10, 'Informations'), (11, 'Statute'), (12, 'Archive')]),
        ),
    ]
