# Generated by Django 3.1.4 on 2021-03-29 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postings', '0007_auto_20210329_1124'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_at', 'title']},
        ),
        migrations.RemoveField(
            model_name='post',
            name='created',
        ),
        migrations.RemoveField(
            model_name='post',
            name='updated',
        ),
    ]
