# Generated by Django 3.1.4 on 2020-12-16 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postings', '0007_post_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='link',
            field=models.URLField(blank=True, default=''),
        ),
    ]
