# Generated by Django 3.1.4 on 2020-12-22 06:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('postings', '0008_auto_20201216_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(db_column='author_username', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='file',
            name='post',
            field=models.ForeignKey(db_column='post_title', on_delete=django.db.models.deletion.CASCADE, related_name='files', to='postings.post'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='post',
            field=models.ForeignKey(db_column='post_title', on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='postings.post'),
        ),
    ]
