# Generated by Django 3.1.4 on 2021-03-29 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postings', '0009_auto_20210330_0030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
