# Generated by Django 3.1.4 on 2021-04-02 03:59

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('postings', '0010_auto_20210330_0053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=imagekit.models.fields.ProcessedImageField(upload_to='photos/%Y/%m/%d'),
        ),
    ]
