# Generated by Django 3.1.4 on 2021-04-18 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('postings', '0012_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='video_key',
        ),
        migrations.AddField(
            model_name='video',
            name='video_link',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='postings.post'),
        ),
    ]
