# Generated by Django 3.1 on 2020-09-02 01:02

from django.db import migrations, models
import posting.models


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0006_auto_20200902_0940'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='name',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='posting',
            old_name='name',
            new_name='author',
        ),
        migrations.AddField(
            model_name='posting',
            name='photo',
            field=models.ImageField(blank=True, upload_to=posting.models.date_upload_to),
        ),
    ]
