# Generated by Django 3.1 on 2020-09-02 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0007_auto_20200902_1002'),
    ]

    operations = [
        migrations.AddField(
            model_name='posting',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
