# Generated by Django 3.1 on 2020-09-02 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0008_posting_view_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='posting',
            name='files',
            field=models.FileField(blank=True, upload_to='%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='posting',
            name='photo',
            field=models.ImageField(blank=True, upload_to='%Y/%m/%d'),
        ),
    ]
