# Generated by Django 3.1 on 2020-09-02 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0009_auto_20200902_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posting',
            name='files',
            field=models.FileField(blank=True, upload_to='files/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='posting',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photo/%Y/%m/%d'),
        ),
    ]
