# Generated by Django 3.1.4 on 2020-12-10 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumni',
            name='year',
            field=models.CharField(max_length=2),
        ),
    ]
