# Generated by Django 3.1.4 on 2020-12-16 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnis', '0002_auto_20201210_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumni',
            name='website',
            field=models.URLField(default=''),
        ),
    ]
