# Generated by Django 3.1.6 on 2021-02-05 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startday', models.DateTimeField()),
                ('endday', models.DateTimeField()),
                ('rooms', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='reservations.room')),
                ('tools', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.tool')),
            ],
        ),
    ]
