# Generated by Django 3.1.6 on 2021-02-15 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='rooms',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='tools',
        ),
        migrations.DeleteModel(
            name='Room',
        ),
        migrations.DeleteModel(
            name='Tool',
        ),
    ]
