# Generated by Django 3.1.1 on 2020-09-23 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_auto_20200923_2258'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='posting',
            options={'ordering': ['-created_datetime']},
        ),
    ]
