# Generated by Django 3.1.4 on 2021-02-16 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='suser_id',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='account',
            name='username',
            field=models.CharField(default='', max_length=255, unique=True),
        ),
    ]
