# Generated by Django 3.1.4 on 2021-03-29 02:51

import auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_auth', '0005_auto_20210329_1142'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='account',
            managers=[
                ('objects', auth.models.UserManager()),
            ],
        ),
    ]
