# Generated by Django 3.1.4 on 2021-03-29 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_auth', '0006_auto_20210329_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
